services:
  genimage:
    build:
      context: ./GenImageAPI
      dockerfile: Dockerfile
    # container_name: gen_image_api
    ports:
      - "8000:8000"
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  dragdiff:
    build:
      context: ./DragDiffusionAPI
      dockerfile: Dockerfile
    # container_name: drag_diff_api
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    ports:
      - "8010:8010"
    depends_on:
      - genimage
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
  backgroundremoval:
    build:
      context: ./RemoveBackgroundAPI
      dockerfile: Dockerfile
    # container_name: background_removal_api
    ports:
      - "8011:8011"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  
  gen3d:
    build:
      context: ./Gen3DAPI
      dockerfile: Dockerfile
    # container_name: gen-3d-api
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postprocess:
    build:
      context: ./PostProcessAPI
      dockerfile: Dockerfile
    # container_name: post_process_api
    ports:
      - "8002:8002"

  postal:
    build:
      context: ./PostalAPI
      dockerfile: Dockerfile
    ports:
      - "8099:8099"

  gaga_client:
    build:
      context: ./cp4101-client
      dockerfile: Dockerfile
    container_name: gaga_client
    ports:
      - "3000:80"
    depends_on:
      - genimage
      - dragdiff
      - backgroundremoval
      - gen3d
      - postprocess
      - postal


volumes:
  huggingface-cache:
    driver: local

